{% set version = "1.2.0" %}

package:
  name: ismip6-antarctic-ocean-forcing
  version: {{ version }}

source:
  url: https://github.com/ismip/ismip6-antarctic-ocean-forcing/archive/{{ version }}.tar.gz
  sha256: c09fa1b1677e5357e976153423a9f1f105883611fcfe05c8be2c45d318fcf1a6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
  run:
    - python >={{ python_min }}
    - dask
    - descartes >=1.1.0
    - gsw
    - imageio
    - matplotlib-base
    - nco
    - netcdf4
    - numpy
    - progressbar2
    - pyremap >=1.4.1
    - pyshp
    - requests
    - scikit-fmm
    - scipy
    - shapely >=2.0
    - xarray

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - ismip6_ocean_forcing
  commands:
    - ismip6_ocean_forcing --version
    - pip check


about:
  home: https://github.com/ismip/ismip6-antarctic-ocean-forcing
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python package for creating ISMIP6 ocean forcing data sets.

extra:
  recipe-maintainers:
    - xylar
